route:
  main:
    enabled: true
    annotations:
      gethomepage.dev/description: Indexer manager
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sh-prowlarr-radarr.svg
      gethomepage.dev/name: Prowlarr
    hostnames:
      - prowlarr.home.jef.app
    parentRefs:
      - name: homelab-gateway
        namespace: gateway
        group: gateway.networking.k8s.io
        kind: Gateway

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce

env:
  TZ: 'Europe/Brussels'
