apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocket-id

helmCharts:
  - name: pocket-id-operator
    version: 0.12.2
    repo: oci://ghcr.io/aclerici38/charts
    includeCRDs: true
    valuesInline:
      instance:
        enabled: false

resources:
  - ./resources/instance.yaml
  - ./resources/default-user.yaml
  - ./resources/platform-owners-group.yaml
  - ./resources/pocket-id-encryption-secret.yaml
  - ./resources/proton-smtp-secret.yaml
