apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmCharts:
  - name: houndarr
    repo: oci://ghcr.io/av1155/charts
    version: 1.13.2
    valuesFile: values.yaml
