apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyform
  labels:
    app.kubernetes.io/name: heyform
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: heyform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heyform
    spec:
      containers:
        - name: heyform
          image: 'heyform/community-edition:v3.0.2'
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: polls
          env:
            - name: APP_LISTEN_PORT
              value: '8000'
            - name: APP_HOMEPAGE_URL
              value: 'https://forms.jef.app'
            - name: MONGO_URI
              value: 'mongodb://mongodb:27017/heyform'
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: polls
                  key: HEYFORM_MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polls
                  key: HEYFORM_MONGO_PASSWORD
            - name: REDIS_HOST
              value: 'valkey'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polls
                  key: valkey-password
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
