apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-repo
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: homelab-repo
  dataFrom:
    - find:
        path: /argocd
        name:
          regexp: repo_.*
      rewrite:
        - regexp:
            source: "repo_(.*)"
            target: "$1"
