apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io/
    version: 1.7.0
    valuesFile: values.yaml
    releaseName: tetragon

resources:
  - resources/egress-policy.yaml
  - resources/grafana-dashboard.yaml
