apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: renovate-secret
  dataFrom:
    - find:
        path: /ci
        name:
          regexp: .*
