route:
  main:
    enabled: true
    annotations:
      gethomepage.dev/description: Movie automation
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sh-radarr.svg
      gethomepage.dev/name: Radarr
      gethomepage.dev/weight: '3'
      gethomepage.dev/widget.type: radarr
      gethomepage.dev/widget.url: http://radarr.media.svc.cluster.local:7878
      gethomepage.dev/widget.key: '{{ `{{HOMEPAGE_VAR_RADARR_APIKEY}}` }}'
      gethomepage.dev/widget.enableQueue: 'true'
    hostnames:
      - radarr.jef.app
    parentRefs:
      - name: homelab-gateway
        namespace: gateway
        group: gateway.networking.k8s.io
        kind: Gateway

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
  data:
    enabled: true
    type: pvc
    existingClaim: media-data
    mountPath: /data

env:
  TZ: 'Europe/Brussels'
