route:
  main:
    enabled: true
    annotations:
      gethomepage.dev/description: TV show automation
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sh-sonarr.svg
      gethomepage.dev/name: Sonarr
    hostnames:
      - sonarr.jef.app
    parentRefs:
      - name: homelab-gateway
        namespace: gateway
        group: gateway.networking.k8s.io
        kind: Gateway

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
  data:
    enabled: true
    type: pvc
    existingClaim: media-data
    mountPath: /data

env:
  TZ: 'Europe/Brussels'
