apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technitium

resources:
  - resources/namespace.yaml
  - resources/pvc.yaml
  - resources/oidc-client.yaml
  - resources/deployment.yaml
  - resources/service-dns.yaml
  - resources/service-web.yaml
  - resources/httproute.yaml
  - resources/udproute.yaml
  - resources/tcproute.yaml
  - resources/gateway.yaml
  - resources/gatewayclass.yaml
  - resources/gatewayclassconfig.yaml
