apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polls
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: polls
  dataFrom:
    - find:
        path: /polls
        name:
          regexp: .*
