apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: '88.3.0'
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values/values.yaml
    includeCRDs: true
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: '18.9.0'
    releaseName: loki
    namespace: observability
    valuesFile: values/loki.yaml
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: '1.11.1'
    releaseName: alloy
    namespace: observability
    valuesFile: values/alloy.yaml
  - name: prometheus-pushgateway
    repo: https://prometheus-community.github.io/helm-charts
    version: '3.8.0'
    releaseName: prometheus-pushgateway
    namespace: observability
    valuesFile: values/pushgateway.yaml

resources:
  - resources/namespace.yaml
  - resources/grafana-httproute.yaml
  - resources/grafana-oidc-client.yaml
  - resources/prometheus-httproute.yaml
  - resources/alertmanager-config.yaml
