revisionHistoryLimit: 3

auth:
  existingSecret: polls
  existingSecretPasswordKey: mongo-password
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

customUsers:
  - existingSecret: polls
    secretKeys:
      name: HEYFORM_MONGO_USERNAME
      password: HEYFORM_MONGO_PASSWORD
      database: HEYFORM_MONGO_DATABASE
    roles:
      - readWrite
      - dbAdmin
