httpRoute:
  enabled: true
  annotations:
    gethomepage.dev/description: Jellyfin media libraries
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin
  hostnames:
    - jellyfin.jef.app
  parentRefs:
    - name: homelab-gateway
      namespace: gateway
      group: gateway.networking.k8s.io
      kind: Gateway
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
persistence:
  media:
    existingClaim: media-data
    mountPath: /data
