# $schema: https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: integrations
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: integrations
  dataFrom:
    - find:
        path: /homepage
        name:
          regexp: .*
      rewrite:
        - transform:
            template: 'HOMEPAGE_VAR_{{ .value | upper | replace "-" "_" }}'
