apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

helmCharts:
  - name: adguard-home
    repo: oci://ghcr.io/helmforgedev/helm
    version: 1.4.11
    valuesFile: values/values.yaml
    includeCRDs: true
    releaseName: adguard-home

patches:
  - patch: |-
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Local
    target:
      kind: Service
      name: adguard-home-adguard-home-dns
  - patch: |-
      - op: add
        path: /spec/rules/0/backendRefs/0/group
        value: ""
      - op: add
        path: /spec/rules/0/backendRefs/0/kind
        value: Service
      - op: add
        path: /spec/rules/0/backendRefs/0/weight
        value: 1
    target:
      kind: HTTPRoute
      name: adguard-home-adguard-home
