apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

helmCharts:
  - name: adguard-home
    repo: oci://ghcr.io/helmforgedev/helm
    version: 1.4.11
    valuesFile: values/values.yaml
    includeCRDs: true
    releaseName: adguard-home

patches:
  - patch: |-
      spec:
        externalTrafficPolicy: Local
    target:
      kind: Service
      name: adguard-home-adguard-home-dns
      namespace: adguard
