fullnameOverride: sealed-secrets-controller

metrics:
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
  dashboards:
    create: true
    annotations:
      grafana_dashboard: '1'
    labels:
      grafana_dashboard: '1'