apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-credentials
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: couchdb-credentials
  dataFrom:
    - find:
        path: /couchdb
        name:
          regexp: .*
