config:
  existingSecret: adguard-home-config

persistence:
  conf:
    size: 256Mi
    storageClass: local-path
  work:
    size: 2Gi
    storageClass: local-path

service:
  web:
    type: ClusterIP
  dns:
    type: LoadBalancer
    loadBalancerIP: '192.168.178.250'

gateway:
  enabled: true
  annotations:
    gethomepage.dev/description: AdGuard DNS
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: sh-adguard-home.svg
    gethomepage.dev/name: AdGuard
  parentRefs:
    - name: homelab-gateway
      namespace: gateway
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - adguard.jef.app
  path: /
  pathType: PathPrefix

ingress:
  enabled: false
