apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: couchdb

helmCharts:
  - name: couchdb
    repo: https://apache.github.io/couchdb-helm
    version: 4.6.3
    valuesFile: values.yaml
    includeCRDs: true
    releaseName: couchdb

patches:
  - target:
      kind: StatefulSet
      name: couchdb-couchdb
      namespace: couchdb
      group: apps
      version: v1
    patch: |
      - op: add
        path: /spec/volumeClaimTemplates/0/apiVersion
        value: v1
      - op: add
        path: /spec/volumeClaimTemplates/0/kind
        value: PersistentVolumeClaim
