apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-encryption
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: pocket-id-encryption
  dataFrom:
    - find:
        path: /pocket-id
        name:
          regexp: .*
