apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proton-smtp
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: proton-smtp
  dataFrom:
    - find:
        path: /pocket-id
        name:
          regexp: proton_.*
      rewrite:
        - regexp:
            source: "proton_(.*)"
            target: "$1"
