apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

helmCharts:
  - repo: oci://codeberg.org/wrenix/helm-charts
    name: forgejo-runner
    releaseName: forgejo-runner
    valuesFile: values/values.yaml
    version: 0.7.6
