apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian

resources:
  - pvc.yaml
  - deployment.yaml
  - cronjob.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml
  - obsidian-livesync-bridge-secret.yaml
