apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livesync-bridge-config
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: livesync-bridge-config
  dataFrom:
    - find:
        path: /obsidian
        name:
          regexp: .*
