apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-manager-copilot
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  target:
    name: vault-manager-copilot
  dataFrom:
    - find:
        path: /obsidian
        name:
          regexp: vault-manager_.*
      rewrite:
        - regexp:
            source: "vault-manager_(.*)"
            target: "$1"
