apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: eso-secret
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: eso-secret
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: homelab-l5-vr
        environmentSlug: prod
        recursive: true
