apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

helmCharts:
  - name: external-dns
    releaseName: external-dns
    valuesFile: ./base/values.yaml
    includeCRDs: true
    repo: https://kubernetes-sigs.github.io/external-dns/
